### ISSUE TITLE
Please Include Additional concepts 

### ISSUE THREAD

**Issue by AishwaryaAnotherrepo** [AishwaryaKR16/Github_Learning#3]
Hi Aishwarya,
           Please include the following topics in the code: 

1. Collections
2. MAPS
3. POM 
4. BDD

**Comment by AishwaryaKR16** [comment]
Hi,
      Will include them in code

**Comment by AishwaryaKR16** [comment]
Added additional concepts

**Comment by AishwaryaAnotherrepo** [comment]
Thanks
